services:

    mariadb:
      build:
        context: requirements/mariadb
        dockerfile: Dockerfile
      volumes:
        - mariadbDatabase:/var/lib/mysql
      networks:
        - inception
      restart: always
      env_file:
        - .env
      secrets:
        - database_pass

    wordpress:
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      volumes: 
        - wordpress:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb
      restart: always
      env_file:
        - .env
      secrets:
        - database_pass
        - wp_pass_root
        - wp_pass

    nginx:
      build:
        context: requirements/nginx
        dockerfile: Dockerfile
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
      restart: always
      env_file:
        - .env
      ports:
      - "443:443"

secrets:
  database_pass:
    file: ../secrets/database_pass.txt
  wp_pass_root:
    file: ../secrets/wp_pass_root.txt
  wp_pass:
    file: ../secrets/wp_pass.txt

networks:
  inception:

volumes:
  mariadbDatabase:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mfahmi/data/mariadbDatabase

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mfahmi/data/wordpress
