FROM debian:bookworm
COPY 



#   ---reminder---
# WordPress PHP code

        # |
        # ▼

# PHP database library
# (mysqli / PDO)

        # |
        # ▼

# MySQL protocol
        # |
        # ▼

# MariaDB server



# WordPress (PHP code)
        # |
        # | calls mysqli/PDO functions
        # ▼
# mysqli / PDO
        # |
        # | sends SQL commands using MySQL protocol
        # ▼
# MariaDB
        # |
        # | executes SQL
        # ▼
# Data returned